# Generated by Django 2.2.6 on 2022-01-11 07:32

import posts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0005_auto_20211211_0032"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="text",
            field=models.TextField(validators=[posts.validators.validate_not_empty]),
        ),
    ]
